config/routes.rb
Rails.application.routes.draw do

  root 'stock_market_game#index'
  get 'stock_market_game/offset' => 'stock_market_game#offset'
  get 'stock_market_game/load' => 'stock_market_game#load'
  post 'stock_market_game/save' => 'stock_market_game#save'

  resources :users, except: [:index, :destroy]
  get '/signup' => 'users#new'
  get '/verification/:code' => 'users#verification'
  get '/user/email_verification_check' => 'users#verification_check'
  
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by email: user_params[:email]
		respond_to do |format|
	    if @user && @user.authenticate(user_params[:password])
	    	session[:user_id] = @user.id
	      format.html { redirect_to root_path, notice: 'Welcome.' }
	      format.json { render json: {status: :created, name: @user.first_name} }
	    else
	      format.html { render :new }
	      format.json { render json: {status: :failed} }
	    end
    end
	end

	def destroy
		session[:user_id] = nil
		respond_to do |format|
			format.html { redirect_to root_path, notice: 'Goodbye.' }
			format.json { render json: {status: "log out successful"} }
		end
	end

	private

    def user_params
      params.require(:session).permit(:email, :password)
    end

end

app/controllers/stock_market_game_controller.rb
class StockMarketGameController < ApplicationController

	include ApplicationHelper

	def index
	  @user = User.new
	end

	def offset
		respond_to do |format|
			format.json { render json: {offset: Time.now.utc_offset}.to_json }
		end
	end


	def save
		respond_to do |format|
			if current_user && current_user.email_verification == "true"
				saved_game = game_params[:saved_game]
				@user = current_user
				if @user.update(saved_game: saved_game)
					format.json { render json: {status: "success"}.to_json }
				else
					format.json { render json: {status: "failed to load game"}}
				end
			else
				format.json { render json: {status: "you are not logged in"}}
			end
		end
	end

	def load
		respond_to do |format|
			if current_user && current_user.email_verification == "true"
				if current_user.saved_game
					format.json { render json: {game: current_user.saved_game , stat: true}.to_json }
				else
					format.json { render json: {status: "there is no game to load" , stat: false}.to_json }
				end
			else
				format.json { render json: {status: "failed to load game", stat: false} }
			end
		end
	end

	private

    def game_params
      params.require(:game).permit!
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update]

	def show
	end

	def new
    @user = User.new
	end

	def edit
		@edit = true
	end

  def create
    @user = User.new(user_params)
    @code = BCrypt::Password.create(@user.email).gsub(/\/+|\.+|\$+/,"")
    @user.email_verification = @code
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        AuthMailer.email_verification_email(@user.email, @code).deliver
        format.html { redirect_to root_path, notice: 'Your account was successfully created, please verify your email.' }
        format.json { render json: {status: :created, name: @user.first_name} }
      else
        format.html { render :new }
        format.json { render json: {status: "failed to create account"} }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'Your account was successfully updated.' }
        format.json { render json: {status: :updated, name: @user.first_name} }
      else
        format.html { render :new }
        format.json { render json: {status: "failed to update your account"} }
      end
    end
  end

  def verification
    @user = User.find_by email_verification: params[:code]
    if @user
      @user.email_verification = "true"
      if @user.save
        @status = true
      else
        @status = false
      end
    else
      redirect_to root_path
    end
  end

  def verification_check
    p "*"*20
    p session[:user_id]
    p "*"*20
    theuser = User.find(session[:user_id])
    respond_to do |format|
      if theuser && theuser.email_verification == "true"
        format.json { render json: {status: true} }
      else
        format.json { render json: {status: "email not verified yet"} }
      end
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :first_name, :middle_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
	  if session[:user_id]
	    return User.find(session[:user_id])
	  else
	    return nil
	  end
	end

end

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Stock Market Game', root_path %></h1>
    </li>
    <li class="toggle-topbar icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.first_name, current_user, id: "user_profile_link", style: 'display:block;', class: "user_links"%></li>
        <li><%= link_to 'logout', logout_path, id: "logout_link", style: 'display:block;', class: "user_links"%></li>
        <li><%= link_to 'login', login_path, id: "login_link", style: 'display:none;', class: "user_links"%></li>
        <li><%= link_to 'signup', signup_path, id: "signup_link", style: 'display:none;', class: "user_links"%></li>
      <% else %>
        <li><%= link_to 'username', current_user, id: "user_profile_link", style: 'display:none;', class: "user_links"%></li>
        <li><%= link_to 'logout', logout_path, id: "logout_link", style: 'display:none;', class: "user_links"%></li>
        <li><%= link_to 'login', login_path, id: "login_link", style: 'display:block;', class: "user_links"%></li>
        <li><%= link_to 'signup', signup_path, id: "signup_link", style: 'display:block;', class: "user_links"%></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Stock Market Game" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

  </body>
</html>

app/views/stock_market_game/index.html.erb
<div id="stock_market_info_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<h2 id="modalTitle">The Stock Market Game</h2>
  <p class="lead">WARNING : Your game will not save if you are not signed in. You can try it out and then sign up to save if you like it.</p>
  <p class="lead">Disclosure : The stock data is from yahoo finance. Please see their fine print to see what the limitations are of this data. I can not guarantee accuracy of the data.</p>
  <p>This is a simple game that is a project of mine. It is by no means a complete application... yet. Check back for improvements Enjoy.</p>
  <p>I will not use, sell, look at, or do anything else with any information collected by this app.</p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<div id="account_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<div id = "login_warning" class = "warning" style = "display:none;">
		<p>Username or Password incorrect, Please try again.</p>
	</div>
	<div class = "row" id = "account_modal_login">
		<%= form_for :session, url: sessions_path, html: {id: "login_form"} do |f|%>
		  <div>
		    <h2>Login</h2>
		  </div>
		  <div>
		    <%= f.label :email %><br>
		    <%= f.email_field :email %>
		  </div>
		  <div>
		    <%= f.label :password %><br>
		    <%= f.password_field  :password %>
		  </div>
		  <div>
		    <%= f.submit("Login", :class => "submit button", :id => "submit") %>
		  </div>
		<% end %>
	</div>
	<div class = "row" id = "account_modal_signup">
		<%= form_for(@user, html: { class: :form, id: "signup_form"}) do |f| %>
		  <% if @user.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
		      <ul>
		      <% @user.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <div>
		    <%= f.label :email %><br>
		    <%= f.email_field :email %>
		  </div>
		  <div>
		    <%= f.label :password %><br>
		    <%= f.password_field  :password %>
		  </div>
		  <div>
		    <%= f.label :first_name %><br>
		    <%= f.text_field :first_name %>
		  </div>
		  <div>
		    <%= f.label :middle_name %><br>
		    <%= f.text_field :middle_name %>
		  </div>
		  <div>
		    <%= f.label :last_name %><br>
		    <%= f.text_field :last_name %>
		  </div>
		  <div>
		    <% button_text = (@edit ? "Save" : "Sign up")%>
		    <%= f.submit(button_text, :class => "submit button", :id => "submit") %>
		  </div>
		<% end %>
	</div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<div class = "row">
	<div class = "large-8 columns panel" id = "sidebar">
		<div class = "row">
			<div class = "large-12 columns">
				<h3>Stocks owned</h3>
			</div>
		</div>
		<div class "row" id = "the_list_below">
			<div class = "large-2 columns">
				<a href = "#" id = "buy_stock_link" class = "button tiny">Buy stock</a>
			</div>
			<div class = "large-10 columns">
				<a href = "#" id = "sell_stock_link" class = "button tiny">Sell stock</a>
			</div>
		</div>
		<div class "row" id = "sidebar_new_stock_search" style = "display: none;">
			<div class = "large-12 columns">
				<form id = "sidebar_get_stock">
					<lable for = "stock_symbol">Enter a Stock Symbol</lable>
					<input name = "stock_symbol" type = "text" id = "sidebar_get_stock_type" autofocus>
					<div id = "enter_value_warning" class = "warning" style = "display:none;"><h5>Please enter an amount</h5></div>
					<lable for = "stock_amount">How Many?</lable>
					<input name = "stock_amount" type = "number" id = "sidebar_get_stock_amount">
					<input type = "submit" value = "Buy" class = "button" id = "buy_sell_button">
				</form>
			</div>
		</div>
		<div id = "sample">
			<div class = "row sidebar_stock" style = "display: none;">
				<form class = "update_button">
					<div class = "large-1 columns symbol"></div>
					<div class = "large-1 columns amount"></div>
					<div class = "large-2 columns priceBought"></div>
					<div class = "large-2 columns currentPrice"></div>
					<div class = "large-2 columns currentValue"></div>
					<div class = "large-2 columns gainLoss"></div>
					<div class = "large-1 columns">
						<a href = "#" class = "buy_stock_link button tiny">Buy</a>
					</div>
					<div class = "large-1 columns">
						<a href = "#" class = "sell_stock_link button tiny">Sell</a>
					</div>
				</form>
			</div>
		</div>
		<div class = "row sidebar_stock">
				<div class = "large-1 columns symbol">Symbol</div>
				<div class = "large-1 columns amount">Amount</div>
				<div class = "large-2 columns priceBought">Purchase Price</div>
				<div class = "large-2 columns currentPrice">Current Price</div>
				<div class = "large-2 columns currentValue">Current Value</div>
				<div class = "large-2 columns left gainLoss">Gain or Loss</div>
		</div>
	</div>
	<div class = "large-1 columns">
	</div>
	<div class = "large-3 columns panel">
		<div class = "row">
			<div class = "large-12 columns">
				<a href="https://www.yahoo.com/?ilc=401" target="_blank"> <img src="https://poweredby.yahoo.com/purple.png" width="134" height="29"/></a>
			</div>
			<div class = "large-12 columns warning" id = "not_signed_in_warning" style = "display:<%= !current_user ? "block" : "none" %>;">
				<h4>Not Saved!</h4>
				<p>login or signup to save</p>
			</div>
			<div class = "large-12 columns warning" id = "no_email_verification_warning" style = "display:<%= current_user && current_user.email_verification != "true" ? "block" : "none" %>;">
				<h4>Still Not Saved!</h4>
				<p>Please verify your email by clicking the link in the email that was sent to you, it may be in your spam folder. After you have done that your game will save within 10 seconds. Do not close this page until you dont see this any more.</p>
			</div>
			<div class = "large-12 columns">
				<h3>Account details</h3>
			</div>
		</div>
		<div class = "row">
			<div class = "large-12 columns">
				<h3>cash :</h3>
				<p id = "bank_cash">10000.00</p>
				<h3>stock value :</h3>
				<p id = "bank_stock_value">0.00</p>
				<h3>total net worth :</h3>
				<p id = "bank_total">10000.00</p>
			</div>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: :form }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <h2><%= @edit ? "Update your " : "Create Your "%>Account</h2>
  </div>
  <% if @edit != true %>
  <div>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field  :password %>
  </div>
  <% end %>
  <div>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <% button_text = (@edit ? "Save" : "Sign up")%>
    <%= f.submit(button_text, :class => "submit button", :id => "submit") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "main">
		<%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class = "main">
		<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div>
	<p><%= @user.first_name %>
		<%= @user.middle_name %>
		<%= @user.last_name %></p>
</div>

app/views/users/verification.html.erb
<% if @status %>
	<h1>All is well.</h1>
	<p>Your email has been verified, your game will save within a minute. When the warning goes away, you know its saved. You can now close this window</p>
<% else %>
	<h1>ut OH, something is not right.</h1>
	<p>Your email has NOT been verified, your game will NOT save. Please contact us.</p>
<% end %>